caprover/caprover

app-backend/src/user/ServiceManager.js
(Thank you so much for this project! I found it today via this Medium post: https://medium.com/@kasra85/how-i-cut-my-heroku-cost-by-400-5b9d0220ce13)
It can be quite useful to have the root domain connected to one of the deployed apps. This PR enables that. Because you can not add an app for the apex domain, this won't conflict with any app names created.
*(As an aside, in the future, I would also rather see it being possible to add any subdomains/hostnames under the root domain as custom domains. That would then require the 'add app' feature and 'add custom domain to app' features to make sure they don't create conflicting names.)*
I have deployed `hugojosefson/captainduckduck:apex` to Docker Hub based on this branch + rename, tried it, and it works. Here's how to test it on a new clean …
=> Allow customDomain === rootDomain.

app-cli/captainduckduck-logout.js
Added splice(i,1) to prevent removal of all trailing machines when logging out of one.
=> Fix logout removing trailing machines

app-cli/captainduckduck-deploy.js
Also, at the end of the build when it says `App is available at:` I think that if https has not yet been enabled for the app concerned, then the link is wrong... it should be http not https.
=> Minor typo / grammar (plus one further comment)

src/datastore/AppsDataStore.ts
Add a duplicate check when renaming.
Clean up the english on the bad name error
Fixes #495
=> check for duplicate name on rename

src/docker/DockerApi.ts
Problem: Caprover cannot read from private registries if imageName has a port as seen in #454
Cause: The `pullImage()` method in `DockerApi.ts` is not parsing the image name correctly because it assumes only one colon in the string (ports would introduce a second colon).
Solution: Refactor the Docker image string parsing more efficiently. Luckily, the _dockerode_ package, which is already a dependency, has a utility function that does precisely this. Let's use that!
=> Fixed image name parsing when using ports

src/datastore/AppsDataStore.ts, src/routes/user/apps/webhooks/WebhooksRouter.ts, src/user/ServiceManager.ts
Generates a new webook token when renaming the app
Returns an error if the trigger endpoint can't extract values from the token
Somewhere we should message the user that they need to update the webhook on any external service that depends on it.
Relates to #490
=> Generate a new webhook on app rename

CONTRIBUTING.md
It seems that we have to first build the project before running the dev script.
Also, I had to manually initialize a docker swarm, but since I had other errors, I'm not sure that it's always the case
=> Add missing step for running environment

template/root-nginx-conf.ejs
The default TLS settings (disabling tls1.0 and 1.1) chosen by CapRover should be applied to the catchall virtualhost as well as the embedded registry.
=> Enforce the same TLS settings for all TLS vhosts

src/utils/GitHelper.ts
It is no longer necessary prepend "ssh://" as sanitizeRepoPathSsh (with e5dd3346) returns already in the correct format
=> fix append ssh

template/server-block-conf.ejs
Adds http2 support for the default nginx script. Http 2 is a backwards compatible upgrade from http 1.1, usable on sites with https and improves load times by uncapping the number of concurrent requests the browser can make for assets, endpoints, etc.
I verified on one of my sites, this is all it takes to enable http 2.
=> Add http2 support for default nginx script

template/base-nginx-conf.ejs
Emitting the NGINX version in the header or on error pages can be a security concern for websites being scanned for NGINX versions with known vulnerabilities.
Hiding this seems like a reasonable default as the benefit of showing it is mostly only useful for debugging purposes and in that case this directive can be removed manually by editing the NGINX conf in Settings.
This doesn't disable the `Server` header entirely, which means it can still be determined someone is running NGINX (to change this requires additional out-of-scope work), but this at least hides the version of NGINX the site is using.
=> Don't emit NGINX version on err pages and in the Server response header

template/server-block-conf.ejs
If you have checked `Force HTTPS by redirecting all HTTP traffic to HTTPS`
Before Fix:
```
curl -i "http://app.example.com/path?var=abc"
HTTP/1.1 302 Moved Temporarily
Location: https://app.example.com/path?var=abc?var=abc
```
After Fix:
```
curl -i "http://app.example.com/path?var=abc"
HTTP/1.1 302 Moved Temporarily
Location: https://app.example.com/path?var=abc
```
=> Fixed Nginx's force SSL redirect URL

CHANGELOG.md, dockerfile-captain.release, src/utils/CaptainConstants.ts
-   Fixed: The following frontend bugs didn't make it to 1.8.1 due to a release mistake
-   Fixed: Logout did not clear cookies. [issue-810](https://github.com/caprover/caprover/issues/810)
-   Fixed: Creating a new app while another app is building breaks the UI [Issue-56](https://github.com/caprover/caprover-frontend/
=> Release  1.8.2

src/user/ServiceManager.ts
Set the CAPROVER_GIT_COMMIT_SHA env var automatically when building
When we are able to and the environment variable isn't already in use, we set the CAPROVER_GIT_COMMIT_SHA env var to the git has that is being deployed. This allows it to be used when building the image and can be copied into the image to use a runtime as well.
Closes #922
=> Set the CAPROVER_GIT_COMMIT_SHA env var automatically when building

src/user/ServiceManager.ts, src/utils/Utils.ts, tests/utils.test.ts
Some apps (eg: [tiredofit/docker-baserow](https://github.com/tiredofit/docker-baserow)) require multiple domains. To reduce friction for the user, we don't want to split the app into multiple sub-apps or require the user to manually change Nginx template config or mess with Le'tsEncrypt certs. The simplest solution is to allow users to add app's subdomain.
For Caprover's server with root domain is root.domain.com, we have app1 at app1.root.domain.com. Allow users to connect subdomain api.app1.root.domain.com.
=> Allow user to connect subdomain of app domain.

src/utils/GitHelper.ts, tests/GitHelper.test.ts
**Problem**
GIT deployment via SSH throws an authorization error if the SSH username is different from 'git'. This happens because the ssh username is hard coded and not taken from the URL
**Fix**
Changed the implementation of the URL sanitizer to take the SSH username from the URL.
**Implementation**
Sanitizing is done in two steps: 1. extract the individual parts from the input URL via a regex (domain, port, repo, ...). 2. construct a new URL by putting the parts together. For the input URL only the domain name and repo name needs to be provided. All other parts of the URL are optional. Default SSH username is 'git' and default port is '22'. '.git' suffix is optional as well.
=> Custom username for SSH git deployment

CONTRIBUTING.md
Added a comment in `CONTRIBUTING.md` about the issues I ran into while trying to develop on recent Mac OS version.
=> Added clarification about /captain for developing on Mac OS catalina or above

src/routes/user/apps/appdefinition/AppDefinitionRouter.ts, src/routes/user/system/SystemRouter.ts
https://github.com/caprover/caprover/commit/7f16a7099bb4c4aac995e5c4ea1470cc53b5a201 introduced a configurable captain sub domain, but the subdomain is still hard-coded in the frontend, which leads to e.g. broken webhook URLs: https://github.com/caprover/caprover-frontend/blob/38ac97e0bd9662ef82ebef8f4b01bc57f44f3dc7/src/containers/apps/appDetails/deploy/Deployment.tsx#L130
This PR makes the API provide the configured `captainSubDomain` to the frontend and is the basis for the related caprover-frontend PR (https://github.com/caprover/caprover-frontend/pull/96) that makes the frontend consume `captainSubDomain` so it uses the correct URLs :)
=> fix: provide configured captainSubDomain to frontend

src/datastore/DataStoreProvider.ts
Close [#1411](https://github.com/caprover/caprover/issues/1411)
When throwing an error without status code it resolve in a 500 error.
Using an error with a status code resolve in more explicit errors.
=> Throw error with status code on empty namespace

src/utils/CaptainConstants.ts
caprover/netdata docker image was upgraded last night (https://github.com/caprover/netdata-docker/pull/3).
Let's bump its version in caprover.
=> chore: upgrade caprover/netdata docker image to the latest version

src/routes/user/apps/appdefinition/AppDefinitionRouter.ts
Domains are frequently copied and pasted and the input may therefore end with spaces or tabs. This PR removes them as the user intended to add the domain without spaces.
=> Trim the customdomain before adding it

src/utils/GitHelper.ts
Fix proposed by @githubsaturn on issue #1520.
According to [git docs](https://git-scm.com/book/en/v2/Git-Tools-Submodules) on submodules the clone flag `--recurse-submodules` should automatically make sure to initialize and update any submodule or nested submodule if any of the submodules in the repository have submodules themselves.
=> Changed clone commands to use ---recurse-submodules

tests/backup.test.ts
As per https://github.com/caprover/caprover/pull/1553#issuecomment-1304282521
(need to hit <a href="https://github.com/caprover/caprover/pull/1555/files?w=1"><img align="center" src="https://user-images.githubusercontent.com/30421456/200122064-30e2e65c-6d3d-4eef-96cd-cd102e92a7b6.png"></a> "Hide Whitespace Changes" to make the diff readable)
=> test: only run backup tests in CI

CONTRIBUTING.md, dev-scripts/dev-clean-run-as-dev-macos-step-1.sh, dev-scripts/dev-clean-run-as-dev-macos-step-2.sh
Hi,
I'm currently working on the frontend but cannot run the backend because I'm using a Monteray version of macOs.
I create the script (copy paste and adapted from the linux one) for specific mac command and security enforcement and document each specific steps in the contributing guide.
I would happy to take any reviews comments.
=> Documentation/docker improve macos documentation and add Catalina and above native support

src/docker/DockerApi.ts
Currently, CapRover v1.10.1 is not able to create services in global mode. A workaround https://github.com/caprover/caprover/issues/1699#issuecomment-1469012497 was suggested to create a global service using Docker CLI, then adding the app in CapRover, but it still doesn't allow for app config updates from the UI due to an 'instance count' validation for non-replicated services.
This PR simplifies the validation limiting it to replicated mode services only, and allowing updates of global mode services to go through.
=> Fix app config update for global mode services

.dockerignore, dockerfile-captain.edge, dockerfile-captain.release
The current Dockerfile used for building production images is not optimized, resulting in larger image sizes. After conducting optimizations, I have successfully reduced the image size from 810MB to 477MB while ensuring the modified Dockerfile maintains functionality.
Changes made to optimize the Dockerfile:
- Removed unnecessary dependencies and packages.
- Utilized multi-stage builds to minimize image layers.
- Employed Alpine Linux as the base image for a smaller footprint.
I have thoroughly tested the modified Dockerfile and verified that it functions correctly in the production environment. The reduced image size will lead to faster deployment times and more efficient resource utilization.
Please review and merge these optimizations into the main branch to improve the efficiency of …
=> Optimize Dockerfile to Reduce Production Image Size

package-lock.json, package.json, src/datastore/DataStore.ts, src/models/AutomatedCleanupConfigs.ts, src/routes/user/apps/appdefinition/AppDefinitionRouter.ts, src/routes/user/system/SystemRouter.ts, src/user/ServiceManager.ts, src/user/system/CaptainManager.ts, src/user/system/DiskCleanupManager.ts
Fix: https://github.com/caprover/caprover/issues/457
=> API skeleton added for automated cleanup

dev-scripts/openstack/single-instance.yml
The goal is to allow CapRover users to be able to easily deploy on any OpenStack cloud, including Infomaniak, SharkTech, VEXXHOST, OVHcloud, and many others.
This PR is for the heat template file to deploy single-instance CapRover.
Slack thread: https://caprover.slack.com/archives/CKQSNHT32/p1716761306596949
=> Added OpenStack Heat template for deploying single-instance CapRover

src/utils/CaptainConstants.ts
Upgrading dockerApiVersion to 1.43
-This package upgrade is required to get cap_add functionality with docker swarm
=> Upgrading Docker API Version to 1.43 in order to add cap_add functionality

src/routes/user/system/SystemRouter.ts, src/user/system/CaptainManager.ts
Fixes for handling initial state with directories not created both on startup and when listing report files.
- **Refactoring work will get rejected** unless it's been communicated with project's maintainers **beforehand**. There is a thousand ways to write the same code. Every time a code is changed, there is a potential for a new bug. We don't want to refactor the code just for the sake of refactoring.
These rules are strictly enforced to make sure that we can maintain the project moving forward.
=> Goaccess fixes 

template/server-block-conf.ejs
The current version of nginx used gives this warning:
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead
In order to avoid this warning the configuration is updated to the new configuration.
=> Change "listen ... http2" directive

CONTRIBUTING.md, src/utils/GitHelper.ts, tests/GitHelper.test.ts
Fixes #2284
- Improve SSH_PATH_RE to ignore extra component paths after port
```diff
- /(?::(?<port>[0-9]{1,5}))?/,
+ /(?::(?<port>[0-9]{1,5}):?)?/,
```
- Remove hardcoded `.git` suffix by parsing it if present only (this is necessary because Azure DevOps don't allow `.git` suffix, in my experience most git servers allow clone with and without `.git` suffix, only Azure Devops don't 🥲)
```diff
- /(?:.git)?\/?\s*$/,
+ /(?:(?<suffix>.git))?\/?\s*$/,
...
- return `ssh://${this.user}@${this.domain}:${this.port}/${this.owner
-  }${this.owner && '/'}${this.repo}.git`
+ return `ssh://${this.user}@${this.domain}:${this.port}/${this.owner
+  }${this.owner && '/'}${this.repo}${this.suffix}`
```  
- Some typo fixings
=> Hotfix: Enhance SSH_PATH_RE on GitHelper to improve URL parsing

src/server.ts, src/user/system/LoadBalancerManager.ts, src/utils/CaptainConstants.ts, src/utils/CaptainInstaller.ts, template/root-nginx-conf.ejs
The serviceExposedPort is only used in the template/root-nginx-conf.ejs and should be the container port that is 3000 (used inside swarm). - https://github.com/search?q=repo%3Acaprover%2Fcaprover+serviceExposedPort&type=code
Continues on https://github.com/caprover/caprover/pull/2220 .
Currently nginx cannot forward traffic to admin/3000 port (is using the one defined in configs.adminPortNumber3000).
=> If configured with CAPTAIN_HOST_ADMIN_PORT nginx should redirect trafic to 3000 that is the container swarm available port
