app-cli/captainduckduck-serversetup.js
app-cli/utils/spinner.js

Add loading state to captainduckduck serversetup
Added a util module for spinner and a higher-order function `apiEndpointWithLoading`, for easier refactor if needed to change spinner plugin.

added spinner for api endpoint in app-cli

---

app-frontend/src/templates/apps.html

input type change text to number for instance count

input type change

---

app-backend/src/datastore/DataStoreImpl.js

Positive number validation added to the updateAppDefinitionInDb

positive number validation added

---

CONTRIBUTING.md

update the top level domain for development

update the top level domain for development

---

app-backend/src/routes/WebhooksRouter.js

system now support Gitlab as repo

Gitlab support

---

app-cli/captainduckduck-deploy.js

Updated config was not being pushed to configstore.

 saveForAppDirectory non update bug fix

---

app-frontend/src/templates/settings.html

design update

---

app-cli/captainduckduck-deploy.js
app-cli/readme.md

Few remarks: handle the reading/storaging the authtoken outside the deploy/login functions so is less coupled
- This can be useful if you want to integrate CI/CD pipeline.
- Makes automatic deployment possible for mono-repos

Stateless (direct) deployment

---

app-frontend/src/oneclick-apps/redis.js

solve #108 
Hi, @githubsaturn!
As the files inside app-frontend and app-backend/dist are the same, I assumed that you run `gulp build` before releasing new versions, so I've added the source code only to app-frontend, but I can update the PR with both files if it's needed.

Add Redis oneclick-app file

---

app-frontend/src/templates/app-details.html
app-frontend/src/templates/apps.html
app-frontend/src/templates/modals/delete-app.html

Update links to documentation

---

docs/recipe-deploy-create-react-app.md

Add static create-react-app recipe

---

docs/recipe-deploy-create-react-app.md

To make the app looks professional, even documentation should show it too. So i  guess changing it to correct spelling will help. :)

Change the spelling of 'technic' to technique

---

app-frontend/src/oneclick-apps/wordpress.js

Minimum requirement updated for Wordpress 4.9.

wordpress 4.9 mysql requirements

---

app-backend/src/utils/GitHelper.js

issue @283 fix

---

src/datastore/AppsDataStore.ts
src/models/AppDefinition.ts
src/models/IServerBlockDetails.ts
src/routes/user/apps/appdefinition/AppDefinitionRouter.ts
src/user/ServiceManager.ts
src/user/system/LoadBalancerManager.ts
src/utils/MigrateCaptainDuckDuck.ts
template/server-block-conf.ejs

- add a new config "websocketSupport" to the app definition
- use this config to add "upgrade headers" to nginx config
fixes #439

add websocket support

---

src/routes/user/apps/appdefinition/AppDefinitionRouter.ts

Validate the fields for the repinfo so it doesn't fail silently.  fixes https://github.com/caprover/caprover-frontend/issues/13

validate the repinfo fields

---

src/docker/DockerApi.ts
src/user/ImageMaker.ts
src/user/ServiceManager.ts

set env vars at build time through docker build --build_args

---

dev-scripts/build_and_push_release.sh

Please make sure you have read [contribution guidelines](https://github.com/caprover/caprover/blob/master/CONTRIBUTING.md#before-contributing). 
- **Refactoring work will get rejected** unless it's been communicated with project's maintainers **beforehand**. There is a thousand ways to write the same code. Every time a code is changed, there is a potential for a new bug. We don't want to refactor the code just for the sake of refactoring.
These rules are strictly enforced to make sure that we can …

added debug release

---

CHANGELOG.md
dev-scripts/build_and_push_release.sh

Please make sure you have read [contribution guidelines](https://github.com/caprover/caprover/blob/master/CONTRIBUTING.md#before-contributing). 
- **Refactoring work will get rejected** unless it's been communicated with project's maintainers **beforehand**. There is a thousand ways to write the same code. Every time a code is changed, there is a potential for a new bug. We don't want to refactor the code just for the sake of refactoring.
These rules are strictly enforced to make sure that we can …

Release PR

---

src/user/ServiceManager.ts
src/user/system/CaptainManager.ts
src/user/system/LoadBalancerManager.ts
src/user/system/SelfHostedDockerRegistry.ts

Please make sure you have read [contribution guidelines](https://github.com/caprover/caprover/blob/master/CONTRIBUTING.md#before-contributing). 
- **Refactoring work will get rejected** unless it's been communicated with project's maintainers **beforehand**. There is a thousand ways to write the same code. Every time a code is changed, there is a potential for a new bug. We don't want to refactor the code just for the sake of refactoring.
These rules are strictly enforced to make sure that we can …

Release 1.7.0

---

src/utils/CaptainConstants.ts

Follow up on https://github.com/caprover/caprover/pull/798

Fixed constants for the release

---

CHANGELOG.md
README.md
dev-scripts/build_and_push_edge.sh
dev-scripts/build_and_push_release.sh
dev-scripts/digitalocean-oneclick-app-generator
dockerfile-captain.edge
package-lock.json
src/datastore/AppsDataStore.ts
src/user/system/LoadBalancerManager.ts
src/utils/CaptainConstants.ts
src/utils/GitHelper.ts

Release 1.8.1
-   New: CapRover now supports ARM processors [issue-445](https://github.com/caprover/caprover/issues/445)
-   Fixed: Logout did not clear cookies. [issue-810](https://github.com/caprover/caprover/issues/810)
-   Fixed: Creating a new app while another app is building breaks the UI [Issue-56](https://github.com/caprover/caprover-frontend/issues/56)

Release 1.8.1

---

README.md

In this PR I did the improvement of the README file to contain the logo and some important information that we have on the CapRover first page but not in the README file.

Improving the README presentation

---

dockerfile-captain.release

According to: https://github.com/caprover/caprover-frontend/blob/master/README.md
```
Thanks for contributing to the frontend code! Since contributors list for CapRover automatically picks up the contributors from the main backend repo, please make a minor update the frontend commit in the dockerfile, so your name will get displayed on the main page as a contributor.
```

Updated the frontend commit

---

src/datastore/AppsDataStore.ts
src/datastore/DataStoreProvider.ts
src/injection/Injector.ts
src/models/AppDefinition.ts
src/routes/user/UserRouter.ts
src/routes/user/apps/appdefinition/AppDefinitionRouter.ts
src/user/ServiceManager.ts
src/utils/CaptainConstants.ts
src/utils/MigrateCaptainDuckDuck.ts
src/utils/Utils.ts

Addressing https://github.com/caprover/caprover/issues/698

Add support for app tokens

---

README.md

Been using Hetzner for some time and it's the best and cheaper way to host Caprover apps
Quick comparison:
| Machine | Hetzner | Vultr | Heroku |
|---|---|---|---|
| 2GB RAM | 5$ | 10$ | 250$ |
| 16GB RAM | 22.35$ | 80$ | 500$ |
Please make sure you have read [contribution guidelines](https://github.com/caprover/caprover/blob/master/CONTRIBUTING.md#before-contributing). 
- **Refactoring work will get rejected** unless it's been communicated with project's maintainers **beforehand**. There is a …

Update price comparison

---

README.md

This commit fixes this weird text

Fix README.md writing math text instead of human text

---

src/utils/CaptainInstaller.ts

Hey there,
Just a quick grammar correction that I noticed on the error print of the initial setup.

corrected error print grammar

---

src/datastore/DataStore.ts

This pull request adds the ability to customise the default NGINX config that every app created will use. It closes the discussion on #977

Adding support for overwriting app defaults NGINX config

---

src/user/system/LoadBalancerManager.ts

feat: expose 443:443/udp in nginx service

---

src/utils/CaptainConstants.ts

https://github.com/caprover/caprover/pull/1355#issuecomment-2451053506

bump nginx version to 1.27.2

---

dockerfile-captain.release

> First of all, thank you for your contribution! 😄
> 
> Please make sure you have read [contribution guidelines](https://github.com/caprover/caprover/blob/master/CONTRIBUTING.md#before-contributing). 
> 
> ### Most important items
> 
> - Make sure to communicate your proposed changes ob our Slack channel beforehand.
> - Large PRs (50+ lines of code) will get rejected due to increased difficulty for review - unless they have been communicated beforehand with project maintainers.
> - **Refactoring work will get rejected** unless it's been communicated with project's maintainers **beforehand**. There is a thousand ways to write the same code. Every time a code is changed, there is a potential for a new bug. We don't want to refactor the code just for the sake of refactoring.
> 
> These rules …

Contributor change for frontend PR "Add ru-RU locale"

---

src/datastore/AppsDataStore.ts

fix #2130
I'm not on slack sorry
I didn't see someone else did a PR (#2330)
So I checked what you asked for:
> Create an app called 1234
```
➜  caprover git:(master) curl 'http://127.0.0.1:3000/api/v2/user/apps/appDefinitions/register?detached=1' -X POST -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0' -H 'Accept: */*' -H 'Accept-Language: en-GB,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br, zstd' -H 'Referer: http://localhost:4500/' -H 'Content-Type: application/json' -H 'x-namespace: captain' -H 'x-captain-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Im5hbWVzcGFjZSI6ImNhcHRhaW4iLCJ0b2tlblZlcnNpb24iOiJ0ZXN0In0sImlhdCI6MTc1OTE1MDEzMCwiZXhwIjoxNzYwODc4MTMwfQ.G1E9JHQAXY9VxfqmVmSJbxLdMEaH0LUDbqjGvOWjqvQ' -H 'Origin: http://localhost:4500' …
```

Allow numbers in project name, fix #2130
